FROM php:5-fpm

RUN apt-get -y update && apt-get install -y \
  php5-mysql \
  git \
  zip \
  unzip

RUN docker-php-ext-install pdo pdo_mysql

# Make sure composer is installed globally
RUN bash -c "curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer"

RUN sed -i "s/^www-data:x:[0-9]*/www-data:x:1000/" /etc/passwd
